resources:
  - name: terraform-ec2
    type: git
    icon:
    source:
      uri: https://github.com/zak-02/terraform-practice.git

jobs:
  - name: deploy-terraform
    plan:
      - get: terraform-ec2
      - task: terraform-init
        params:
          AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
          AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: hashicorp/terraform
          inputs:
            - name: terraform-ec2
          run:
            path: terraform
            args: ["-chdir=terraform-ec2", "init"]

      - task: terraform-apply
        params:
          AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
          AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: hashicorp/terraform
          inputs:
            - name: terraform-ec2
          run:
            path: terraform
            args: ["-chdir=terraform-ec2", "apply", "-auto-approve"]
